spring:
  application:
    name: profile
  datasource:
   tomcat:
     initial-size: 2   
security:
 oauth2:
   resource:
     accessTokenUri: http://18.217.187.31:8090/oauth/check_token
     userAuthorizationUri: http://18.217.187.31:8090/oauth/authorize
     userInfoUri: http://18.217.187.31:8090/user
     jwt:
       keyUri: http://18.217.187.31:8090/oauth/token_key
server:
 port: 8004
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.217.187.31:8761/eureka/
  instance:
    instanceId: portal
    hostname: 18.217.187.31:8004
