server:
  port: 8761
  
spring:
  application:
    name: trello-eureka
    datasource:
    tomcat:
      initial-size: 2
      
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
